sudo: false
language: go

go:
  - "1.11.x"
  - tip

os:
  - linux
  - osx
  - windows

env:
  - GO111MODULE=on

cache:
  directories:
    - $(go env GOCACHE)

install:
  - GO111MODULE=off go get -u golang.org/x/lint/golint
  - GO111MODULE=off go get -u golang.org/x/tools/cmd/goimports

stages:
  - lint
  - examples
  - test

jobs:
  include:
    - stage: lint
      script:
        - diff <(goimports -d $(find . -type f -name '*.go')) <(echo -n "")
        - make lint
      go: "1.11.x"
      os: osx
    - stage: examples
      script:
        - ./_example/build.sh
      go: "1.11.x"
      os: osx

script:
  - go test -race ./...

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
    - os: windows
