name: tests
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go: ['stable']
    steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: ${{ matrix.go }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@master
    - name: Running go tests
      env:
        GO111MODULE: on
      run: make test

  wasm:
    name: Cross compile to WASM
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v6
      with:
        go-version: 'stable'
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@master
    - name: Build
      env:
        GOOS: 'js'
        GOARCH: 'wasm'
      run: go build ./...

  examples:
    name: Build examples
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: 'stable'
        id: go
      - name: Check out code into the Go module directory
        uses: actions/checkout@master
      - name: Building go examples
        env:
          GO111MODULE: on
        run: ./_example/build.sh

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-go@v6
        with:
          go-version: 'stable'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
