// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/testapi/testapi.proto

package testapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request message with generic fields for testing.
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`              // Unique identifier for the request.
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`    // Payload of the request, can carry any data.
	Sequence      int32                  `protobuf:"varint,3,opt,name=sequence,proto3" json:"sequence,omitempty"` // Sequence number for ordering or tracking requests.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_internal_testapi_testapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testapi_testapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_internal_testapi_testapi_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Request) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *Request) GetSequence() int32 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

// Response message with generic fields for testing.
type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`                                    // Corresponding request's unique identifier.
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`                            // Result or response content.
	StatusCode    int32                  `protobuf:"varint,3,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"` // Status code indicating success or type of error.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_internal_testapi_testapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_internal_testapi_testapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_internal_testapi_testapi_proto_rawDescGZIP(), []int{1}
}

func (x *Response) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Response) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *Response) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

var File_internal_testapi_testapi_proto protoreflect.FileDescriptor

const file_internal_testapi_testapi_proto_rawDesc = "" +
	"\n" +
	"\x1einternal/testapi/testapi.proto\x12\x1efangrpcstream.internal.testapi\"O\n" +
	"\aRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x05R\bsequence\"S\n" +
	"\bResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x1f\n" +
	"\vstatus_code\x18\x03 \x01(\x05R\n" +
	"statusCode2\x84\x01\n" +
	"\x14FangRpcStreamService\x12l\n" +
	"\x13BidirectionalStream\x12'.fangrpcstream.internal.testapi.Request\x1a(.fangrpcstream.internal.testapi.Response(\x010\x01B:Z8github.com/joeycumines/go-fangrpcstream/internal/testapib\x06proto3"

var (
	file_internal_testapi_testapi_proto_rawDescOnce sync.Once
	file_internal_testapi_testapi_proto_rawDescData []byte
)

func file_internal_testapi_testapi_proto_rawDescGZIP() []byte {
	file_internal_testapi_testapi_proto_rawDescOnce.Do(func() {
		file_internal_testapi_testapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_testapi_testapi_proto_rawDesc), len(file_internal_testapi_testapi_proto_rawDesc)))
	})
	return file_internal_testapi_testapi_proto_rawDescData
}

var file_internal_testapi_testapi_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_testapi_testapi_proto_goTypes = []any{
	(*Request)(nil),  // 0: fangrpcstream.internal.testapi.Request
	(*Response)(nil), // 1: fangrpcstream.internal.testapi.Response
}
var file_internal_testapi_testapi_proto_depIdxs = []int32{
	0, // 0: fangrpcstream.internal.testapi.FangRpcStreamService.BidirectionalStream:input_type -> fangrpcstream.internal.testapi.Request
	1, // 1: fangrpcstream.internal.testapi.FangRpcStreamService.BidirectionalStream:output_type -> fangrpcstream.internal.testapi.Response
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_testapi_testapi_proto_init() }
func file_internal_testapi_testapi_proto_init() {
	if File_internal_testapi_testapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_testapi_testapi_proto_rawDesc), len(file_internal_testapi_testapi_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_testapi_testapi_proto_goTypes,
		DependencyIndexes: file_internal_testapi_testapi_proto_depIdxs,
		MessageInfos:      file_internal_testapi_testapi_proto_msgTypes,
	}.Build()
	File_internal_testapi_testapi_proto = out.File
	file_internal_testapi_testapi_proto_goTypes = nil
	file_internal_testapi_testapi_proto_depIdxs = nil
}
