// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: internal/testapi/testapi.proto

package testapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FangRpcStreamService_BidirectionalStream_FullMethodName = "/fangrpcstream.internal.testapi.FangRpcStreamService/BidirectionalStream"
)

// FangRpcStreamServiceClient is the client API for FangRpcStreamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition for the bidirectional gRPC stream.
type FangRpcStreamServiceClient interface {
	// The RPC method for establishing a bidirectional stream.
	BidirectionalStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error)
}

type fangRpcStreamServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFangRpcStreamServiceClient(cc grpc.ClientConnInterface) FangRpcStreamServiceClient {
	return &fangRpcStreamServiceClient{cc}
}

func (c *fangRpcStreamServiceClient) BidirectionalStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Request, Response], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FangRpcStreamService_ServiceDesc.Streams[0], FangRpcStreamService_BidirectionalStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Request, Response]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FangRpcStreamService_BidirectionalStreamClient = grpc.BidiStreamingClient[Request, Response]

// FangRpcStreamServiceServer is the server API for FangRpcStreamService service.
// All implementations must embed UnimplementedFangRpcStreamServiceServer
// for forward compatibility.
//
// Service definition for the bidirectional gRPC stream.
type FangRpcStreamServiceServer interface {
	// The RPC method for establishing a bidirectional stream.
	BidirectionalStream(grpc.BidiStreamingServer[Request, Response]) error
	mustEmbedUnimplementedFangRpcStreamServiceServer()
}

// UnimplementedFangRpcStreamServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFangRpcStreamServiceServer struct{}

func (UnimplementedFangRpcStreamServiceServer) BidirectionalStream(grpc.BidiStreamingServer[Request, Response]) error {
	return status.Errorf(codes.Unimplemented, "method BidirectionalStream not implemented")
}
func (UnimplementedFangRpcStreamServiceServer) mustEmbedUnimplementedFangRpcStreamServiceServer() {}
func (UnimplementedFangRpcStreamServiceServer) testEmbeddedByValue()                              {}

// UnsafeFangRpcStreamServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FangRpcStreamServiceServer will
// result in compilation errors.
type UnsafeFangRpcStreamServiceServer interface {
	mustEmbedUnimplementedFangRpcStreamServiceServer()
}

func RegisterFangRpcStreamServiceServer(s grpc.ServiceRegistrar, srv FangRpcStreamServiceServer) {
	// If the following call pancis, it indicates UnimplementedFangRpcStreamServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FangRpcStreamService_ServiceDesc, srv)
}

func _FangRpcStreamService_BidirectionalStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FangRpcStreamServiceServer).BidirectionalStream(&grpc.GenericServerStream[Request, Response]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FangRpcStreamService_BidirectionalStreamServer = grpc.BidiStreamingServer[Request, Response]

// FangRpcStreamService_ServiceDesc is the grpc.ServiceDesc for FangRpcStreamService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FangRpcStreamService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fangrpcstream.internal.testapi.FangRpcStreamService",
	HandlerType: (*FangRpcStreamServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BidirectionalStream",
			Handler:       _FangRpcStreamService_BidirectionalStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "internal/testapi/testapi.proto",
}
